pygments:     true
exclude:      ["WE-settings.xml", "CNAME", "*.less", "*.cmd"]

port:        8778

markdown:    redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "with_toc_data", "underline"]